### ISSUE TITLE
Start work on the simulation!

### ISSUE THREAD

**Issue by Gustavwk** [johannesmols/Caelicus#25]

**Comment by parzival3** [comment]
```plantuml
@startuml
hide empty description

[*] --> Reset
Reset --> Start
note left of Start {
Set the time of the simulations and
Create the list of missions
}
Start : Set Time 
Start : Set List of Missions
Start --> Time
Time --> CheckMission
note right of CheckMission {
Here we check if a mission was
completed in the running missions
If there is a mission to fire at
this time we enqueue it to the list
of runningMissions.
}

note right of Time {
Here we check that the time is not over
and proceed with the other evetns
}

note right of GenerateRandomEvent {
In this state we generate
random event like wind or traffic
}

note right of AdvanceClock {
Here we just advance the time,
I don't know if this shuold be the
first state after Start

}

note right of ProcessEvents {
Here the WorldController will process
all the events and equeue new Events
like the end of a mission
}

CheckMission --> GenerateRandomEvent
GenerateRandomEvent --> AdvanceClock
AdvanceClock --> ProcessEvents
ProcessEvents --> Time
Time --> [*]
@enduml
```

![image](https://user-images.githubusercontent.com/4521714/97783149-208ba880-1b96-11eb-9c59-31208aea20e0.png)

**Comment by johannesmols** [comment]
Hi @parzival3, I'm done with the cleanup and put a lot of work into the setup of the simulation. I created a simulation manager that can receive multiple requests for simulation with specific parameters and will then run the situations in parallel. It is quite complicated but what is important is the different classes I made.


1. **SimulationManager** - Keeps track of simulations, starts and stops them, retrieves results, etc.
2. **Simulation** - The actual simulation will be performed in here. I made an empty template that accepts the simulation parameters
3. **SimulationParameters** - The parameters to a simulation
4. **SimulationProgress** - Encapsulates data that can be sent back to the UI thread to display status information (currently just a string that is displayed in a text area on the UI)
5. **SimulationResult** - Encapsulates the result data to be sent back to the application. Currently also just containing a string but feel free to change it whatever is appropriate.

The **simulation parameters** look like this for now:

```csharp
public class SimulationParameters
    {
        public Guid SimulationIdentifier { get; set; }

        public int RandomSeed { get; set; }

        public Graph<VertexInfo, EdgeInfo> Graph { get; set; } = new Graph<VertexInfo, EdgeInfo>();

        public List<Tuple<Vehicle, int>> Vehicles { get; set; } = new List<Tuple<Vehicle, int>>();

        public float SimulationSpeed { get; set; } = 1f;
    }
```
Each simulation gets a unique identifier and a random seed. The random seed is the same for all simulations so please use it for generating random events so that all simulations play out the same way. Then there is the graph object and a list of vehicles along with how many there are for each vehicle type. And then finally a simulation speed if we want to make it update only once a second for example. It's important to note that the list of vehicles contains several different vehicles, so the simulation needs to also run the vehicle types completely separately. Maybe it would be better to start a new simulation for each vehicle type. Currently, I start 5 simulations from the UI thread with 1, 2, 3, 4 and 5 vehicles each just to test it out for now.

The **simulation** itself looks like this:

```csharp
public class Simulation
    {
        private readonly SimulationParameters _parameters;

        public Simulation(SimulationParameters parameters)
        {
            _parameters = parameters;
        }

        public async Task<SimulationResult> Simulate(IProgress<SimulationProgress> progress, CancellationToken cancellationToken)
        {
            progress.Report(new SimulationProgress(_parameters.SimulationIdentifier, $"Starting simulation with  { _parameters.Vehicles.FirstOrDefault()?.Item2 } vehicles"));

            // TODO: Perform the actual simulation
            await Task.Delay(1000);

            // Use this snippet to repeatedly check for cancellation in each iteration of the simulation
            if (cancellationToken.IsCancellationRequested)
            {
                progress.Report(new SimulationProgress(_parameters.SimulationIdentifier, $"Stopped simulation with { _parameters.Vehicles.FirstOrDefault()?.Item2 } vehicles"));
                throw new TaskCanceledException();
            }

            progress.Report(new SimulationProgress(_parameters.SimulationIdentifier, $"Finished simulation with { _parameters.Vehicles.FirstOrDefault()?.Item2 } vehicles"));

            return new SimulationResult(_parameters.SimulationIdentifier, "Success");
        }
    }
```

It is an asynchronous method and takes in a progress object and cancellation token. The progress object allows you to send status updates back to the UI thread, and with each simulation step we should check whether the user wants to cancel the simulation using the cancellation token. You can use this template to start building something.

Once the simulation is done it returns a **simulation result** to the simulation manager. As said before, this currently just contains a string but can be whatever you want.

The whole thing looks this from the UI. You can select the graph, simulation speed, and select the vehicle types to use. Maybe we could add an input field for the range of number of vehicles to use (e.g. we want to simulate how it is to have 1 drone and up to 100 drones, and everything in between). The updates from the simulations are printed in the text area along with their unique identifier. In the bottom left we could maybe display a map with live updates if we feel like it (?). Could be difficult with multiple parallel simulations.

![image](https://user-images.githubusercontent.com/11809436/97800457-96931c80-1c35-11eb-9d4d-6ea221b19802.png)

**Comment by parzival3** [comment]
Nice work man :-), yesterday a was taking a day off from study :-) but now I'm back. I think we are missing a parameter for the missions right?

**Comment by johannesmols** [comment]
![image](https://user-images.githubusercontent.com/11809436/97909923-44dbb680-1d49-11eb-8213-2a0165b52ae5.png)

@parzival3 I added some controls to how many vehicles there will be in a simulation. So I changed the sim parameters to just contain one Vehicle object which is the template of the vehicle, and then a number of how many of those vehicles there should be in the simulation. Make sure to merge it into your branch and resolve conflicts from the new types :) Will generate the orders next.

**Comment by johannesmols** [comment]
@parzival3 I saw you added an empty to find a path in the graph. Should I implement that for you? :)

**Comment by parzival3** [comment]
Yeah man, I'm having a really hard time to merge my work into yours. I'm using plain git and all the files are seeing as binary ... I'm struggling to just merge the two branches 🙊 can you take a look?

**Comment by parzival3** [comment]
The files have a weird encoding and git struggles to merge them. If you do something like `git status` it tells you that the files are binary. I've spent the whole morning trying to just merge my work 😭 😞

**Comment by parzival3** [comment]
I think we should convert all the files in UTF-8 encoding otherwise it's very hard to work together

**Comment by johannesmols** [comment]
Oh that's weird. I did merge your code into one of mine but am getting a few errors because you are using the Vehicle objects that I removed. I would recommend you to use GitKraken which makes it very easy to see the difference between two branches. It can even integrate with third party compare tools like WinMerge or BeyondCompare to go in more detail and fix single lines.

Maybe try doing that and merge the current master branch into yours and fix the errors that are introduced because of the new vehicle types. Afterwards when that is all working we can move it into master. Are you otherwise done with an initial version?

I'm implementing a pathfinding function in the Graph object now but will do that on master as well.

**Comment by parzival3** [comment]
Do you have any weird settings in .gitconfig ?

**Comment by johannesmols** [comment]
There is no .gitconfig but I know this can be problem when you are on Linux. Try running `git add --renormalize .` [(SO)](https://stackoverflow.com/a/50645024) and see if that helps.

**Comment by parzival3** [comment]
No no I'm on Windows 🤣

**Comment by johannesmols** [comment]
Oh okay :D Then I honestly don't know. I would imagine Gitkraken could solve it.

**Comment by parzival3** [comment]
I've decided to merge your branch into mine and pushed the missing changes on my branch

**Comment by parzival3** [comment]
Now it's complaining about a division by zero 🤣 if I try to run the simulation. Most likely the Vehicle class when instantiated throws an exception

**Comment by johannesmols** [comment]
Are you done with your simulation so I can have a look and clean things up a bit? Or are you still working on it?

**Comment by parzival3** [comment]
In my mind is working  😂 but yeah take a look

**Comment by parzival3** [comment]
I was trying to look if it was easy to have another class that implements main in order to test our simulation without blazor but I couldn't find anything

**Comment by johannesmols** [comment]
Shouldn't be a big issue since all the core logic is written in pure C# and not Razor components. We could add another project to the solution that uses these classes. Then you have to generate graphs, vehicles, etc. of course since that's coming from Blazor.

**Comment by johannesmols** [comment]
> Now it's complaining about a division by zero 🤣 if I try to run the simulation. Most likely the Vehicle class when instantiated throws an exception

![image](https://user-images.githubusercontent.com/11809436/98003175-b6ba0b80-1dee-11eb-9115-b1c57fe149f9.png)

The exception is right btw, you are dividing zero by zero 😉 You are using the Capacity of the List which is 0 by default if not set otherwise. Not sure what you are trying to achieve there. Lists are always dynamic in size. If you need a fixed size you can use arrays (or set capacity to something, but then it can still be less).

I'm looking through your code now.

**Comment by parzival3** [comment]
I'm trying to give a base to each drone. And that's not a division is a reminder. 0%0 should work without any problems 🤔🤔🤔

**Comment by parzival3** [comment]
@johannesmols  Capacity is not the number of elements in the list?

**Comment by johannesmols** [comment]
@parzival3 I changed a lot of stuff on your branch now. It was mostly refactoring, prettifying and removing unnecessary stuff. I merged the different classes you had into one because I don't think it makes much sense to split that up when you share the same resources (graph, orders, vehicles) anyway.

So at least it runs now but it's not really doing anything yet. I will look into the "actual" simulation later and how that works.

**Comment by parzival3** [comment]
> ![image](https://user-images.githubusercontent.com/11809436/98013081-300b2b80-1dfa-11eb-964f-37305a76730b.png)
> 
> Not in C# apparently haha. But I solved it anyway by cycling through the list of bases and assigning them in a for loop. I will push the changes when I'm done refactoring.
> 
> > @johannesmols Capacity is not the number of elements in the list?
> 
> No that is Count :) Capacity sets an upper limit of how many items there are allowed to be in a List.

No no you are right.... That was pretty bad 😞 of course the reminder is a division.
